CREATE TABLE `audit_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `request_id` varchar(64) NOT NULL,
  `event_id` varchar(64) NOT NULL,
  `event_type` varchar(50) NOT NULL,
  `action` varchar(20) NOT NULL,
  `operator_id` varchar(64) NOT NULL,
  `operator_name` varchar(100) DEFAULT NULL,
  `resource_type` varchar(30) NOT NULL,
  `resource_id` varchar(100) DEFAULT NULL,
  `resource_version` varchar(30) DEFAULT NULL,
  `result` varchar(20) NOT NULL,
  `duration_ms` int NOT NULL,
  `detail` text,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `extra` json DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ix_audit_logs_event_id` (`event_id`),
  KEY `idx_event_type_action` (`event_type`,`action`),
  KEY `ix_audit_logs_request_id` (`request_id`),
  KEY `ix_audit_logs_resource_id` (`resource_id`),
  KEY `ix_audit_logs_operator_id` (`operator_id`)
) ENGINE=InnoDB AUTO_INCREMENT=8852 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;