[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tavily-research-kit"
version = "0.0.1"
description = "openJiuwen plugin"
readme = "README.md"
requires-python = ">=3.11"


[tool.setuptools.packages.find]
where = ["src"]
include = ["tavily_research_kit*"]
